name: catholic_prayers
description: Catholic Prayers Project.
publish_to: 'none'

version: 1.4.6+23

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Firebase & Notification
  firebase_core: ^1.18.0
  firebase_analytics: ^9.1.10
  firebase_crashlytics: ^2.8.2
  firebase_messaging: ^11.4.2
  flutter_local_notifications: ^9.6.1
  # Util
  intl: ^0.17.0
  package_info: ^2.0.2
  provider: ^6.0.3
  dio: ^4.0.6
  json_serializable: ^6.2.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3
  sqflite: ^2.0.2+1
  desktop_window: ^0.4.0
  share_plus: ^4.0.8
  collection: ^1.16.0
  timeago: ^3.2.2
  timeago_flutter: ^1.1.0
  # Design
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  flutter_spinkit: ^5.1.0
  flutter_styled_toast: ^2.1.3
  flutter_advanced_drawer: ^1.3.2
  shimmer: ^2.0.0
  introduction_screen: ^3.0.2
  lottie: ^1.3.0
  collapsible_sidebar: ^2.0.1+2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lotties/
    - google_fonts/
  fonts:
    - family: PyiDaungSu
      fonts:
        - asset: assets/fonts/pyidaungsu/pyidaungsu_regular.ttf
          weight: 400
        - asset: assets/fonts/pyidaungsu/pyidaungsu_bold.ttf
          weight: 700
        - asset: assets/fonts/pyidaungsu/pyidaungsu_numbers.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/regular_wght.ttf
        - asset: assets/fonts/montserrat/italic_wght.ttf
          style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/lato_thin.ttf
          weight: 100
        - asset: assets/fonts/lato/lato_thinitalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/lato/lato_light.ttf
          weight: 300
        - asset: assets/fonts/lato/lato_lightitalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/lato_regular.ttf
          weight: 400
        - asset: assets/fonts/lato/lato_italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lato/lato_bold.ttf
          weight: 700
        - asset: assets/fonts/lato/lato_bolditalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/lato_black.ttf
          weight: 900
        - asset: assets/fonts/lato/lato_blackitalic.ttf
          weight: 900
          style: italic
